# Generated by Django 6.0.7 on 2026-08-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20, unique=True)),
                ('title', models.TextField()),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('main_category', models.CharField(blank=True, max_length=255, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=255, null=True)),
                ('recommendation_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
