# Generated by Django 6.0.6 on 2026-08-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=20, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('categories', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('related', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
