# Generated by Django 6.0.7 on 2026-08-29 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='img_url',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='sub_category',
        ),
    ]
